film:
  image_width: 700
  image_height: 700
  bucket_width: 128
  bucket_height: 128
  filter_radius: 1.8
  filter_method: none # leave to none when denoising
  denoise: false
#  crop:
#    start: [300,300]
#    end: [400,400]
camera:
  position: [ 3.9,0.0,0.0 ]
  target: [ 0.0,0.0,0.0 ]
  fov: 39.0
  aperture: 0.0
  focal_distance: 0.0 # camera target is used if you do not provide this field
sampler:
  max_samples: 12
  method: sobol
renderer:
  depth_limit: 1
  threads: 1
  clamp: 15.0
scene:
  background_color: [ 0.0,0.0,0.0 ]