film:
  image_width: 2000
  image_height: 2000
  bucket_width: 128
  bucket_height: 128
  filter_radius: 1.8
  filter_method: none
  denoise: true
  crop:
#    start: [200,50]
#    end: [300,200]
camera:
  position: [0.0,2.0,-8.0]
  target: [0.0,3.5,-0.5]
  fov: 60.0
  aperture: 0.2
sampler:
  max_samples: 100
  method: sobol
renderer:
  depth_limit: 12
  threads: 10
scene:

window:
  scale: 1.5
