film:
  image_width: 1000
  image_height: 1000
  bucket_width: 128
  bucket_height: 128
  filter_radius: 1.8
  filter_method: none # leave to none when denoising
  denoise: false
#  crop:
#    start: [300,300]
#    end: [400,400]
camera:
  position: [0.0,0.0,4.0]
  target: [0.0,0.0,0.0]
  fov: 38.0 # degrees
  aperture: 0.0
  focal_distance: 0.0 # camera target is used if you do not provide this field
sampler:
  max_samples: 12
  method: sobol
renderer:
  depth_limit: 8
  threads: 11 # do not use more threads than cores available, it won't improve performance
  clamp: 10.0
scene:
  background_color: [0.0,0.0,0.0]
